# Configuração do Cloudflare Pages
# Documentação: https://developers.cloudflare.com/pages/

name = "openleads-strategy-hub"
compatibility_date = "2024-01-01"

# Configurações de Build
[build]
command = "npm run build"
cwd = ""

[build.upload]
format = "directory"
dir = "dist"

# Configurações de Deploy
[env.production]
# Adicione variáveis de ambiente de produção aqui
# VITE_API_URL = "https://api.openleadsstrategy.com"

[env.preview]
# Variáveis para ambiente de preview
# VITE_API_URL = "https://api-preview.openleadsstrategy.com"

# Headers de Segurança e Performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.jpg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.svg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Redirects e Rewrites para SPA
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

