# Configuração do Cloudflare Pages
# Documentação: https://developers.cloudflare.com/pages/

name = "openleads-strategy-hub"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Note: Build configuration is done via Cloudflare Dashboard or CLI
# Set build command: npm run build
# Set build output: dist
